TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0
  escape_vel: 0
  holonomic_robot: false