axis_linear:
    x: 1
    y: 0
scale_linear:
    x: 0.5
    y: 0.5
scale_linear_turbo:
    x: 1.0
    y: 1.0
axis_angular:
    yaw: 2
scale_angular:
    yaw: 0.5
scale_angular_turbo:
    yaw: 1.0
enable_button: 10
enable_turbo_button: 8