weights_path: $(find track_racecar)/config/yolo
config_path: $(find track_racecar)/config/yolo

yolo_model:
  config_file:
    name: traffic_light_and_sign.cfg
  weight_file:
    name: traffic_light_and_sign.weights
  threshold:
    value: 0.9
  detection_classes:
    names:
      - traffic_light_red
      - traffic_light_yellow
      - traffic_light_green
      - speed_limit_30
      - speed_limit_60
      - stop_sign